### ISSUE TITLE
Feature request, robot configuration JSON

### ISSUE THREAD

**Issue by dehann** [GearsAD/SynchronySDK.jl#3]
One feature that is very useful is the ability to store a robot configuration in the database.  Previous versions of the [code stored configuration data in the first pose](https://github.com/dehann/Caesar.jl/blob/fd2ce8c7387da81d98e52d67eb0dc0d2f575b15c/src/cloudgraphs/CloudGraphIntegration.jl#L963) of a session.

Is there a way to add a JSON robot configuration somewhere in the robot or session nodes of the DB?

**Comment by dehann** [comment]
please

**Comment by dehann** [comment]
also see: https://github.com/dehann/Caesar.jl/blob/fd2ce8c7387da81d98e52d67eb0dc0d2f575b15c/src/cloudgraphs/CloudGraphIntegration.jl#L998

**Comment by GearsAD** [comment]
How about a dictionary (JSON) that you can attach/retrieve directly from a robot instance?

**Comment by GearsAD** [comment]
I can do this tonight, should be a quick one.

**Comment by dehann** [comment]
Thanks!

**Comment by dehann** [comment]
example usage:
https://github.com/dehann/Caesar.jl/blob/example/synchronyhauv/examples/lcmserver/synchrony.jl

```julia
function setRobotParameters!(cg::CloudGraph, session::AbstractString)
  hauvconfig = Dict()
  hauvconfig["robot"] = "hauv"
  hauvconfig["bTc"] = [0.0;0.0;0.0; 1.0; 0.0; 0.0; 0.0]
  hauvconfig["bTc_format"] = "xyzqwqxqyqz"
  # currently unused, but upcoming
  hauvconfig["pointcloud_description_name"] = "BSONpointcloud"
  hauvconfig["pointcloud_color_description_name"] = "BSONcolors"
  # robotdata = json(hauvconfig).data

  # Actually modify the databases
  insertrobotdatafirstpose!(cg, session, hauvconfig)
  nothing
end
```

**Comment by GearsAD** [comment]
https://github.com/GearsAD/SynchronySDK.jl/blob/636de107aeaf9eab1df1c81e134c7ba4262521b7/examples/1_CreateRobot.jl#L32-L36

**Comment by dehann** [comment]
I added a comment to the commit about maybe doing `conf::Dict{String, Any}` instead?  JSON should be fine with a wider class of Dict types?
